name: FB Traffic Monster
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31194
title: FB Traffic Monster
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c5b96'
    - '#a1bf2a'
    - '#ffffff'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.13690017512999475
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.9346272794064134
purpose: []
