name: FB Traffic Monster
favicon: null
layout_spectrum: 0.41285
typography_spectrum: 0.5147032751701772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13690017512999475
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.9346272794064134
purpose: []
